spec:
  destination:
    server: https://kubernetes.default.svc
  default:
    repoURL: https://github.com/zbitmanis/gitops-infra.git
    helm:
      valueFiles:
        - values.yaml
  source:
    targetRevision: HEAD
  gitops:
    applications:
      gitOpsGatekeeper:
        appPath: 'applications/gatekeeper'
        namespace: 'gatekeeper-system'
        isEnabled: true
        isEnabedAutoSync: true
      gitOpsIngressNginx:
        appPath: 'applications/ingress-nginx'
        isEnabled: true
        isEnabedAutoSync: true
      gitOpsAwsLoadBalancerController
        targetRevision: v1.0
        appPath: applications/aws-load-balancer-controller
        isEnabled: true
        isEnabedAutoSync: true
