{{- if .Values.spec.gitops.applications.gitOpsAwsLoadBalancerController.isEnabled | default false }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: aws
  project: {{ .Values.spec.gitops.applications.gitOpsAwsLoadBalancerController.project |default "default" }}
  source:
    path: {{ .Values.spec.gitops.applications.gitOpsAwsLoadBalancerController.appPath }}
    repoURL: {{ .Values.spec.gitops.applications.gitOpsAwsLoadBalancerController.repoURL | default .Values.spec.default.repoURL }}
    targetRevision: {{ .Values.spec.gitops.applications.gitOpsAwsLoadBalancerController.targetRevision | default .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
          {{- range $val := .Values.spec.default.helm.valueFiles }}
            - {{ $val }}
          {{- end}}
{{- if .Values.spec.gitops.applications.gitOpsAwsLoadBalancerController.isEnabedAutoSync | default false }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    retry:
      limit:  5
      backoff:
        duration: 5s 
        factor: 2
        maxDuration: 3m
{{- end }}
{{- end }}
