{{- if .Values.spec.gitops.applications.gitOpsIngressNginx.isEnabled | default false }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.gitops.applications.gitOpsIngressNginx.namespace | default 'ingress-nginx-system' }}
  project:  {{ .Values.spec.gitops.applications.gitOpsIngressNginx.project | default 'default' }}
  source:
    path: {{ .Values.spec.gitops.applications.gitOpsIngressNginx.appPath }}
    repoURL: {{ .Values.spec.gitops.applications.gitOpsIngressNginx.repoURL | default .Values.spec.default.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
          {{- range $val := .Values.spec.default.helm.valueFiles }}
            - {{ $val }}
          {{- end}}
{{- if .Values.spec.gitops.applications.gitOpsIngressNginx.isEnabedAutoSync | default false }}
  syncPolicy:
    automated: {}
    retry:
      limit: {{ .Values.spec.gitops.sync.limit | default 5 }}
      backoff:
        duration: {{ .Values.spec.gitops.sync.backoff.duration | default 5s }}
        factor: 2
        maxDuration: 3m
{{- end }}
{{- end }}
